### PR TITLE
Display ONNX logging output

### PR DESCRIPTION
**Pull request by lmagder**
-Connect ONNX logging output to WinRT FileLoggingSession and also OutputDebugString
-Change default level from ORT_LOGGING_LEVEL_ERROR to ORT_LOGGING_LEVEL_WARNING

I'm not sure if this was going somewhere else before and this change is redundant but I couldn't find it. If so I'll close this.

### CODE REVIEW

**Comment by axodox** [comment]
I will merge this, but I will restructure the code so it can be reused better (e.g. create a helper class for logging in my Axodox.Common lib, and abstract out the Windows only code). I will let you know how it goes.

**Comment by axodox** [comment]
Merged, thanks for the help.
ThanksThankYouGIF

**Comment by lmagder** [comment]
No problem, thanks for taking a look! 👍 Not sure if you'll ever hit this, but on https://github.com/axodox/axodox-common/blob/f9fb2b61d7d6f62424d02ae740772f06f01fd067/Axodox.Common.Shared/Infrastructure/Logger.cpp#L84 it will crash if somebody logs a message with printf qualifiers in it like "%s", (unlikely to happen unless there is a bug though 😃)

**Comment by axodox** [comment]
Thanks for the tip.

**Pull request merged**
